apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app-gitlab
  namespace: argocd
spec:
  project: default
  
  # Source - Local GitLab repository (cluster-internal URL)
  source:
    repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/iot-abelhadj.git
    targetRevision: main
    path: dev
  
  # Destination
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true