apiVersion: v1
kind: Service
metadata:
  name: gitlab-webservice-nodeport
  namespace: gitlab
  labels:
    app: webservice
    release: gitlab
spec:
  type: NodePort
  ports:
  - name: http
    port: 8181
    targetPort: 8181
    nodePort: 30081
    protocol: TCP
  selector:
    app: webservice
    release: gitlab