global:
  hosts:
    domain: gitlab.local
    https: false
  ingress:
    enabled: false
    configureCertmanager: false 
  edition: ce
  
  appConfig:
    enableUsagePing: false
    enableSeatLink: false

nginx-ingress:
  enabled: false

gitlab-runner:
  install: false

prometheus:
  install: false

registry:
  enabled: false

grafana:
  enabled: false


gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
      
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitaly: {}
  gitlab-shell:
    minReplicas: 1
    
  kas:
    enabled: false
  gitlab-exporter:
    enabled: false

postgresql:
  metrics:
    enabled: false

redis:
  metrics:
    enabled: false