SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"
LOGIN = "abelhadj"
SERVER_HOSTNAME = "#{LOGIN}S"
WORKER_HOSTNAME = "#{LOGIN}SW"

Vagrant.configure("2") do |config|
    config.vm.box = "generic/alpine318"
    config.vm.box_version = "4.3.12"

    config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    config.ssh.extra_args = ["-t", "sudo -i"]
    
    # Server VM (Controller)
    config.vm.define SERVER_HOSTNAME do |server|
        server.vm.hostname = SERVER_HOSTNAME
        server.vm.network "private_network", ip: SERVER_IP
        server.vm.provider "virtualbox" do |vb|
            vb.name = SERVER_HOSTNAME
            vb.memory = 2048
            vb.cpus = 1
        end
        server.vm.provision "shell", path: "scripts/server.sh", args: [SERVER_IP, WORKER_IP, LOGIN], privileged: true 
    end

    # Worker VM (Agent)
    config.vm.define WORKER_HOSTNAME do |worker|
        worker.vm.hostname = WORKER_HOSTNAME
        worker.vm.network "private_network", ip: WORKER_IP
        worker.vm.provider "virtualbox" do |vb|
            vb.name = WORKER_HOSTNAME
            vb.memory = 1024
            vb.cpus = 1
        end
        worker.vm.provision "shell", path: "scripts/worker.sh", args: [SERVER_IP, WORKER_IP, LOGIN], privileged: true 
    end
end
